---
name: 'Sync project'

on:
  push:
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: 'checkout source repo'
        uses: actions/checkout@v3
        with:
          token: ${{secrets.GH_TOKEN}}
          path: source

      - name: 'checkout target repo'
        uses: actions/checkout@v3
        with:
          repository: dev1-sg/.github
          token: ${{secrets.GH_TOKEN}}
          path: target

      - name: 'sync to profile'
        run: |
          rsync -av source/README.md target/profile/README.md
          cd target
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync from dev1-sg/project"
          git push
